kind: PersistentVolume
apiVersion: v1
metadata:
  name: eventstore-pv-volume
  labels:
    type: local
spec:  
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
